version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: ajuda-ai-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker_password
      POSTGRES_DB: ajuda-ai
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
